dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
dotenv: .env
networks:
  default: development
  kovan:
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  deployment:
    verify: False
  ganache-local2:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
